// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcxAS9IZRQCW3dRstL8WyOsJ-7DmxxtfE',
    appId: '1:1071491598436:web:094fe73219e73d24f43771',
    messagingSenderId: '1071491598436',
    projectId: 'chat-app-548a0',
    authDomain: 'chat-app-548a0.firebaseapp.com',
    storageBucket: 'chat-app-548a0.appspot.com',
    measurementId: 'G-2LLG6ZCF2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa52DEGQcXJ66SlwZLIDfc0oagaEdLvoc',
    appId: '1:1071491598436:android:41d01a93cf154358f43771',
    messagingSenderId: '1071491598436',
    projectId: 'chat-app-548a0',
    storageBucket: 'chat-app-548a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD84dNFkKGINeYzLYHKB5_RCCf_WsDEkKY',
    appId: '1:1071491598436:ios:30bfc030533ddffef43771',
    messagingSenderId: '1071491598436',
    projectId: 'chat-app-548a0',
    storageBucket: 'chat-app-548a0.appspot.com',
    iosClientId: '1071491598436-7vs8asee6ekkp7f35huncb811lhku6kl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD84dNFkKGINeYzLYHKB5_RCCf_WsDEkKY',
    appId: '1:1071491598436:ios:dfbd043b93876a68f43771',
    messagingSenderId: '1071491598436',
    projectId: 'chat-app-548a0',
    storageBucket: 'chat-app-548a0.appspot.com',
    iosClientId: '1071491598436-6cfl9mje4kldk4udqtnf3e40jhl5cn16.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
